# Header Names
X_BOBB_HEADER = "X-Bobb-Header"
X_BOBB_OPTIONAL_HEADER = "X-Bobb-Optional-Header"

# Error Messages
ERROR_INVALID_BOBB_HEADER = "Invalid Bobb header"
ERROR_INVALID_OPTIONAL_HEADER = "Invalid Bobb optional header"

# Default Values
DEFAULT_HOP_COUNT = 255
DEFAULT_PRIORITY = 0
DEFAULT_ENCRYPTION_ALGO = "None"

# HTTP Status Codes
STATUS_SUCCESS = 200
STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_SERVER_ERROR = 500

# Basestation
BASESTATION = "basestation"

# Satellite Functions
SATELLITE_FUNCTION_DISASTER_IMAGING = "disaster-imaging"
SATELLITE_FUNCTION_WHALE_TRACKING = "whale-tracking"
SATELLITE_FUNCTION_WINDFARM_MONITORING = "windfarm-monitoring"
